### PR TITLE
Replicate router enhancements from SIMS

### PR DESCRIPTION
**Pull request by curtisupshall**
# Overview
Replicates some of the router improvements devised in SIMS, as needed by [SIMSBIOHUB-96](https://apps.nrs.gov.bc.ca/int/jira/browse/SIMSBIOHUB-96)

### CODE REVIEW

**Review by al-rosenthal — DISMISSED** [review]
🐶

**Review by NickPhura — DISMISSED** [review]
🐍

**Review by al-rosenthal — APPROVED** [review]
🧑‍🎤

**Review by KjartanE — APPROVED** [review]
🐱

**Pull request merged**
